input: .
output: .retype
url: https://fortygazelle700.github.io/Tilt-Docs/
branding:
  title: TILT
  label: v1.0 - Docs
links:
  - text: Getting Started
    link: https://retype.com/guides/getting-started/
editor:
  enabled: false
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
